server:
  port: 5555
  context-path: /
  jsp-servlet:
    init-parameters:
      development: true

logging:
  level: info

spring:
#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: update
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.110.224:3306/xuekui?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
    username: root
    password: xuekui123
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource

mybatis:
  mapper-locations: classpath:mapper/*.xml
  config-location: classpath:mybatis-config.xml
  type-aliases-package: com.fzu.demo.web.entity

cai :
    downloadtimer : 0 0/1 * * * ?
    statisticstimer : 0 0/1 * * * ?


